### ISSUE TITLE
pixel to dimesionless

### ISSUE THREAD

**Issue by andrewdavis3** [BjornFJohansson/pydna#44]
trying to run  Pydna Gel Electrophoresis Simulation, keep getting the error below

>>> Gel([ st,[pcr_prod]] , gel_len=16).run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/site-packages/pydna/gel.py", line 1379, in run
    noise, Itol, detectlim, title, FWTM, False)
  File "/home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/site-packages/pydna/gel.py", line 728, in gelplot_imshow
    pxl_x = int(round(gel_width * res))
  File "/home/linuxbrew/.linuxbrew/Cellar/python3/3.6.2/lib/python3.6/site-packages/pint/quantity.py", line 441, in __int__
    raise DimensionalityError(self._units, 'dimensionless')
pint.errors.DimensionalityError: Cannot convert from 'pixel' to 'dimensionless'

**Comment by klprint** [comment]
I got the same and I was told that there will be a bugfix in the near future. See [Issue 43](https://github.com/BjornFJohansson/pydna/issues/43)

**Comment by andrewdavis3** [comment]
thanks!
I ran:
pip3 uninstall pint
pip3 install pint==0.7.2

And it works just fine

**Comment by BjornFJohansson** [comment]
Hi, the new version 2.0.2 should work also with a newer version of pint.
