### ISSUE TITLE
[3.1.3] Biopython 1.7.9 breaks restriction digestion

### ISSUE THREAD

**Issue by marcus-r-kelly** [BjornFJohansson/pydna#69]
`DSeq.cut` breaks when Biopython version is 1.7.9. In both examples below, the pydna version is 3.1.3

With python3.8 and Biopython 1.7.8:
`>>> from pydna.dseq import Dseq
>>> duplex=Dseq("GGGATCCAAA")
>>> import Bio
>>> from Bio.Restriction import BamHI
>>> duplex.cut(BamHI)
(Dseq(-6)
GG
CCCTAG, Dseq(-8)
GATCCAAA
GTTT)   `

Whith python 3.9 and Biopython 1.7.9
`Python 3.9.5 (default, Jun  4 2021, 12:28:51)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydna.dseq import Dseq
>>> duplex=Dseq("GGGATCCAAA")
>>> from Bio.Restriction import BamHI
>>> duplex.cut(BamHI)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cellar/users/mrkelly/miniconda3/envs/asp/lib/python3.9/site-packages/pydna/dseq.py", line 1370, in cut
    enzymes = [
  File "/cellar/users/mrkelly/miniconda3/envs/asp/lib/python3.9/site-packages/pydna/dseq.py", line 1373, in <listcomp>
      if e.search(
  File "/cellar/users/mrkelly/miniconda3/envs/asp/lib/python3.9/site-packages/Bio/Restriction/Restriction.py", line 549, in search
    cls.dna = FormattedSeq(dna, linear)
  File "/cellar/users/mrkelly/miniconda3/envs/asp/lib/python3.9/site-packages/Bio/Restriction/Restriction.py", line 168, in __init__
    stringy = str(seq)
  File "/cellar/users/mrkelly/miniconda3/envs/asp/lib/python3.9/site-packages/Bio/Seq.py", line 326, in __str__
         return self._data.decode("ASCII")
AttributeError: 'str' object has no attribute 'decode'
>>>      `

**Comment by BjornFJohansson** [comment]
Yes, try the 4.0.0a9 instead. The underlying Biopython  Seq and SeqRecord were changed quite a bit between 
1.78 and 1.79.

**Comment by BjornFJohansson** [comment]
@marcus-r-kelly can I close this?

**Comment by marcus-r-kelly** [comment]
Yes, thank you.
